server:
  #端口号
  port: 8081
  #项目名，如果不设定，默认是 / 8080


spring:
  datasource:
    url: jdbc:mysql://106.52.86.31:3306/taopao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useTimezone=True&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
